### ISSUE TITLE
Make possible to force application update

### ISSUE THREAD

**Issue by p-pavel** [sbt/launcher#12]
It would be nice if sbt-launcher could work with snapshot revisions, updating them if needed. At least forcing the application update via properties will unlock the scenario of distributing application properties say on the web and the launcher updating to the last snapshot.

Currently "force update" is hardcoded to false in launcher/launcher-implementation/src/main/scala/xsbt/boot/Launch.scala@147. 

replacing false to true produces "correct" behaviour -- application is updated only if changed

**Comment by eed3si9n** [comment]
I don't think this would happen for sbt launcher since it might cause various downstream issues, like trying to hit the internet when it's offline.
