### ISSUE TITLE
sbt-launch no longer published to repo?

### ISSUE THREAD

**Issue by joost-de-vries** [sbt/launcher#15]
Circleci uses a repo url to keep track of new versions of sbt-launch so that they can make them available on their ci platform.
I think travis does something similar. 
The repo url they're following [http://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/](http://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/) has sbt-launch versions up to including 0.13.9. But nothing after that.

As a result CI platforms like CircleCI (and I think [Travis as well](https://github.com/travis-ci/travis-ci/issues/4527)) require custom downloading of sbt which makes sbt work less "out of the box" on CI services.

So my question is: is there a repo to which new versions of sbt-launch are published? Or can sbt-launch versions higher than 0.13.9 continue being published to bintray?

groetjes

**Comment by eed3si9n** [comment]
First, I'd recommend against using Bintray URLs directly. Instead the following URL should be used: https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/

> But nothing after that.

A repackaged launcher for 0.13.11 is published there.

**Comment by joost-de-vries** [comment]
Hi Eugene,

My mistake: I somehow assumed the list was sorted numerically. But it's alphabetically ofcourse.

Tx and have a nice sunday
