### ISSUE TITLE
sbt-launch.jar can not run in background

### ISSUE THREAD

**Issue by invkrh** [sbt/launcher#20]
Just want to know it is a feature or bug ?

``` bash
$ java -jar  ~/Downloads/sbt-launch.jar &
```

will be `Stopped` like the following

```
[1]+  Stopped                 java -jar ~/Downloads/sbt-launch.jar
```

Once it go to frontground, it continue to work

```
$ fg
[info] Loading project definition from ...
....
```

**Comment by pfluegkuffer** [comment]
I have the same issue. After a while in the foreground (5-10sec.) the process can continue in the background. But initially it need to run in the foreground. Why is that?

**Comment by eed3si9n** [comment]
There's a bit more info in https://github.com/sbt/sbt/issues/4718, so I am going to close this.
