### ISSUE TITLE
error: object xsbt.boot.ListMap is not a value

### ISSUE THREAD

**Issue by cunei** [sbt/launcher#22]
This seems to be quite a puzzle. Observe:
### steps
```
$ cat build.sbt
libraryDependencies += "org.scala-sbt" % "launcher" % "1.0.0"
$ cat project/build.properties 
sbt.version=0.13.13
$ cat Test.scala 
object X {
  val z = _root_.xsbt.boot.ListMap
}
```
### problem
```
$ sbt compile
[info] Compiling 1 Scala source to /home/cunei/activities/test-vari/test-xsbt-boot-listmap/target/scala-2.10/classes...
[error] /home/cunei/activities/test-vari/test-xsbt-boot-listmap/Test.scala:2: object xsbt.boot.ListMap is not a value
[error]   val z = xsbt.boot.ListMap
[error]                     ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 1 s, completed Nov 17, 2016 9:13:29 PM
```
### expectation
The test should compile successfully.
The bizarre part is that the object classfile is clearly in the jar: there is a ``xsbt/boot/ListMap$.class`` file and scalap duly lists its methods.
The companion object appears in the source file: https://github.com/sbt/launcher/blob/v1.0.0/launcher-implementation/src/main/scala/xsbt/boot/ListMap.scala#L33
### notes
Using the launcher v0.13.8, all works:
```
$ sbt compile
[info] Compiling 1 Scala source to /home/cunei/activities/test-vari/test-xsbt-boot-listmap/target/scala-2.10/classes...
[success] Total time: 1 s, completed Nov 17, 2016 9:10:28 PM
```
I must admit I ran out of ideas. Maybe something related to proguard? Any clue is welcome.

**Comment by eed3si9n** [comment]
> The test should compile successfully.

launcher JAR is proguarded, so you can't expect it to function as a library. I wouldn't be surprised if the companion object alone is gone.

**Comment by cunei** [comment]
I tried to publish locally a non-proguarded version of the launcher, and the test compiles ok. I can probably use this custom version to launch dbuild.
The space saving, it turns out, is less than 780KB. Is it really worth it using proguard for the launcher?

**Comment by eed3si9n** [comment]
I don't know what the total jar size will be without proguarding. But like I said, using launcher as library is not its intended use case, so thus far it's been ok. Is there something specific Dbuild is doing that's special?

**Comment by cunei** [comment]
Plain: 1 197 609 bytes, proguarded: 418 912 bytes; in relative terms it does what it is supposed to, of course. However, the sizes are pretty small in absolute terms. Unless the launcher is used on a microcontroller, I don't think the saving would make any difference at all, in practice.
dbuild at startup generates a list of repositories using:
```
          val listMap = xsbt.boot.ListMap(resolvers.toSeq.reverse: _*)
          (new xsbt.boot.ConfigurationParser).getRepositories(listMap)
```
It does a lot of other things with the launcher, actually, but somehow `ListMap` and `getRepositories` fail with the proguarded version. I can probably just package the same logic in a separate library, without modifying the standard launcher.
I was actually just wondering about the rationale behind the proguard-ification of the launcher, and the use cases for which it was intended.

**Comment by eed3si9n** [comment]
The Proguarded sbt launcher is a stand alone application that resolves arbitrary module from launchconfig, downloads the jars, and runs it. Currently it's around 1.2 MB, likely including Scala and Ivy bundled in.

**Comment by cunei** [comment]
Yes, that much I know. I am asking why that much effort for 780KB, considering that the typical computer systems that will run it will have 10'000 times that much memory onboard. Embedded systems are not going to use the sbt launcher to download jars from the net: they will just package everything together and proguard the result.
Again, I am not suggesting we remove proguard, I am just inquiring about the reasons why it is there.

**Comment by cunei** [comment]
With that I mean: do you happen to have any historical insight about the reasons why it was introduced? Or was it just to make it as small as possible, just in case?

**Comment by eed3si9n** [comment]
> Again, I am not suggesting we remove proguard, I am just inquiring about the reasons why it is there.

I'm not 100% sure since I didn't first create it, but my understanding is that it's made to be as small as possible for faster startup time of `sbt` command on terminal. Since the launcher portion is used only to launch the mothership (sbt) and relegates itself immediately it makes sense to keep that portion small.
