### ISSUE TITLE
Adding sbt-launcher dependency breaks syntax highlighting in IntelliJ IDEA

### ISSUE THREAD

**Issue by foxmk** [sbt/launcher#25]
**Problem**

If you add `"org.scala-sbt" % "launcher" % "1.0.0"` to sbt project dependencies, and import that project in IntelliJ IDEA, syntax highlighting will break:

![image](https://cloud.githubusercontent.com/assets/5107532/22534029/bb434f26-e8f1-11e6-8e55-5b9214cf62bc.png)

Tested on IDEA 2016.3.4 on macOS.

**Comment by eed3si9n** [comment]
It's probably expected since launcher is Proguarded. See also https://github.com/sbt/launcher/issues/22#issuecomment-304138828
