### ISSUE TITLE
MaxMetaspaceSize is limited even if the JVM command line property is not given

### ISSUE THREAD

**Issue by cleverkidd** [sbt/launcher#39]
Hi,

Is there any reason why `MaxMetaspaceSize` is limited by default?

https://github.com/sbt/launcher/blob/1.x/launcher-implementation/src/main/scala/xsbt/boot/ServerApplication.scala#L258-L277

in general, this space is out of heap space (= does not depend on heap size) and is not limited in JVM (from openjdk):
```c
size_t MetaspacePool::calculate_max_size() const { 
  return FLAG_IS_CMDLINE(MaxMetaspaceSize) ? MaxMetaspaceSize : MemoryUsage::undefined_size();
} 
```

**Comment by eed3si9n** [comment]
Looks like this was added for the older sbt server design going back to Activator - https://github.com/sbt/launcher/commit/0c120409c9590ca0e08c2f87510f1236c7de02f5
