### ISSUE TITLE
Multiple repository override files

### ISSUE THREAD

**Issue by eed3si9n** [sbt/launcher#6]
This is a proposal for a new feature
## ~/.sbt/repositories.d/ directory

launcher will look into this directory and process each files in alphabetical order, similar to SysV init.
## `k00default.properties`

`k00default.properties` could be the default priority level. so if you make a file name that sorts after `k00default.properties` like `s00custom.properties` (`s` for single user) it will be processed afterwards.
## `[meta]`

Add

```
[meta]
  repositories: append | overwrite | disabled
```

This adds control command for the repository files. For example, Activator can now use `append` with `x01activator.properties`.
- `append`: appends the list of repositories to at the end
- `overwrite`: replaces the list of repositories
- `disabled`: ignores the file (used when you're traveling/debugging etc.)

**Comment by havocp** [comment]
This would certainly be easier/safer for Activator's scenario.
